In [1]:
#in order using tensorflow in jupyter,
#Ref link: http://stackoverflow.com/questions/37061089/trouble-with-tensorflow-in-jupyter-notebook
#source activate tensorflow
#which ipython
#which jupyter
#which python

import tensorflow as tf

In [2]:
savefile = './model.ckpt'

In [3]:
#using tf.truncated_normal to set random values.
weights = tf.Variable(tf.truncated_normal([2,3]))

In [4]:
bias = tf.Variable(tf.truncated_normal([3]))

In [5]:
saver = tf.train.Saver()

In [6]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print("Weights:")
    print(sess.run(weights))
    print("Bias")
    print(sess.run(bias))
    
    #save the model
    saver.save(sess,savefile)

Weights:
[[-0.42519793 -0.70773017  1.48292446]
 [-1.00800109 -1.16150451 -1.72595966]]
Bias
[ 0.42354047  0.33569616  1.7159791 ]


In [7]:
#loading variables

#remove the previous weights and bias
tf.reset_default_graph()

In [8]:
weights = tf.Variable(tf.truncated_normal([2,3]))
bias = tf.Variable(tf.truncated_normal([3]))

In [9]:
saver = tf.train.Saver()     #Main point

In [10]:
#tf.train.Saver.restore() function loads the saved data into weights and bias.

with tf.Session() as sess:
    saver.restore(sess,savefile) ########Main point###########
    print(sess.run(weights))
    print(sess.run(bias))

[[-0.42519793 -0.70773017  1.48292446]
 [-1.00800109 -1.16150451 -1.72595966]]
[ 0.42354047  0.33569616  1.7159791 ]


# Save a Trained Model

In [14]:
tf.reset_default_graph()

In [17]:
from tensorflow.examples.tutorials.mnist import input_data
import numpy as np

In [18]:
learning_rate = 0.001

In [19]:
n_input = 784

In [20]:
n_classes = 10

In [22]:
mnist = input_data.read_data_sets(".",one_hot=True)

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting ./train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting ./train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting ./t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting ./t10k-labels-idx1-ubyte.gz


In [23]:
features = tf.placeholder(tf.float32,[None,n_input])
labels = tf.placeholder(tf.float32, n_classes)

In [ ]:
weights = tf.Variable(tf.random_normal([n_input]))
bias = tf.Variable(tf.random_normal([n_class]))